### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by alishah730** [vdenotaris/spring-boot-security-saml-sample#40]
Please help how to run behind proxy.

I'm getting below error

17:14:45.295 [main] ERROR org.opensaml.saml2.metadata.provider.HTTPMetadataProvider - Error retrieving metadata from https://idp.ssocircle.com/idp-meta.xml
java.net.UnknownHostException: idp.ssocircle.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0_144]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_144]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_144]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_144]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673) ~[?:1.8.0_144]
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:477) ~[?:1.8.0_144]

**Comment by vdenotaris** [comment]
Custom configurations are not in the scope of this project.
