### ISSUE TITLE
Error on redirect

### ISSUE THREAD

**Issue by Itachi-Uchiha78** [vdenotaris/spring-boot-security-saml-sample#46]
Hi,

thanks for sharing this precious SAML-SP attempt, this standard is really hard to get, and moreover some good tutorial on it.

Now your project works after a certificate refresh.
I can reach the default choose IDP page, once logged in SSOCircle it gives me error on redirect.

I'm currently using my free SSOCircle user, already validated on the Official Spring SAML Sample tutorial.

I've got to change the EntityID to upload metadata to SSOCircle which says the current is already used.
I've changed:

`metadataGenerator.setEntityId("com:mytest:spring:sp"); `

in WebSecurityConfig.class but the project fails to start:

```
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_73]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.23-dev]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: org.opensaml.common.SAMLException: Error loading metadata
	... 67 more
Caused by: org.opensaml.saml2.metadata.provider.MetadataProviderException: Metadata for entity com:vdenotaris:spring:sp and role {urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor wasn't found
	at org.springframework.security.saml.context.SAMLContextProviderImpl.populateLocalEntity(SAMLContextProviderImpl.java:319) ~[spring-security-saml2-core-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.security.saml.context.SAMLContextProviderImpl.populateLocalContext(SAMLContextProviderImpl.java:216) ~[spring-security-saml2-core-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.security.saml.context.SAMLContextProviderImpl.getLocalEntity(SAMLContextProviderImpl.java:107) ~[spring-security-saml2-core-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.security.saml.SAMLDiscovery.processDiscoveryRequest(SAMLDiscovery.java:183) ~[spring-security-saml2-core-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	... 66 more
```

Thanks in advance

**Comment by Itachi-Uchiha78** [comment]
Solved:

https://github.com/vdenotaris/spring-boot-security-saml-sample/issues/22
